// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARHvXmTVccv0c5AZmNZ5_-9rBCZJ2t72E',
    appId: '1:483386443225:web:1f25e37e0613d1c8c5c5c8',
    messagingSenderId: '483386443225',
    projectId: 'tracksiteproapp-d13a5',
    authDomain: 'tracksiteproapp-d13a5.firebaseapp.com',
    storageBucket: 'tracksiteproapp-d13a5.firebasestorage.app',
    measurementId: 'G-8122QPNL89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfjSEnrCCmMn_7_IFraC_Cyvy8V6NrotA',
    appId: '1:483386443225:android:8c435f8424d12edcc5c5c8',
    messagingSenderId: '483386443225',
    projectId: 'tracksiteproapp-d13a5',
    storageBucket: 'tracksiteproapp-d13a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtlBHj63AW2DdMJC78aJvnItfv0Cj2jl0',
    appId: '1:483386443225:ios:c02bd72eceb34abac5c5c8',
    messagingSenderId: '483386443225',
    projectId: 'tracksiteproapp-d13a5',
    storageBucket: 'tracksiteproapp-d13a5.firebasestorage.app',
    iosBundleId: 'com.example.trackSiteProApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtlBHj63AW2DdMJC78aJvnItfv0Cj2jl0',
    appId: '1:483386443225:ios:c02bd72eceb34abac5c5c8',
    messagingSenderId: '483386443225',
    projectId: 'tracksiteproapp-d13a5',
    storageBucket: 'tracksiteproapp-d13a5.firebasestorage.app',
    iosBundleId: 'com.example.trackSiteProApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARHvXmTVccv0c5AZmNZ5_-9rBCZJ2t72E',
    appId: '1:483386443225:web:57b195103573fc8bc5c5c8',
    messagingSenderId: '483386443225',
    projectId: 'tracksiteproapp-d13a5',
    authDomain: 'tracksiteproapp-d13a5.firebaseapp.com',
    storageBucket: 'tracksiteproapp-d13a5.firebasestorage.app',
    measurementId: 'G-XQ0F9PEMXH',
  );

}